### ISSUE TITLE
[Workflows] Create a workflow for round-robin push assignment (opposed to auto-dispatcher pull)

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#117]
A client asked for round-robin assignment using automations similar to the old guide using bot behaviors. This would take a list of workers as a sequence and assign new tickets to them in order as a cycle (e.g. A, B, C, A, B, C, ...).

Example of cycles/modulo in Twig:

```twig
{% set worker_ids = [1,2,3,4] %}

{# Using cycle #}
{% for i in 0..25 %}
{{cycle(worker_ids, i)}}
{% endfor %}

{# Using modulo #}
{% set counter = 0 %}
{% for i in 0..25 %}
{{worker_ids[counter % worker_ids|length]}}
{% set counter = counter + 1 %}
{% endfor %}
```

Example automation using modulo + counter:

```yaml
start:
  set:
    counter@int: 0
    worker_ids@csv: 1,2,3,4
    
  while:
    if@bool: yes
    do:
      await:
        worker_id@int: {{worker_ids[counter % worker_ids|length]}}
      set:
        counter@int: {{counter + 1}}
```

**Comment by jstanden** [comment]
```yaml
workflow:
  name: example.ticket.auto_assignment
  version: 2025-01-16T00:03:44Z
  description: Auto-assign new tickets round-robin to a list of workers
  website: https://cerb.ai/resources/workflows/
  requirements:
    cerb_version: >=11.0 <11.1
    cerb_plugins: cerberusweb.core,
  config:
    chooser/bucket_ids:
      label: Buckets for auto-assignment
      record_type: bucket
      multiple@bool: yes
    chooser/worker_ids:
      label: Workers to round robin assign
      record_type: worker
      record_query: isDisabled:n
      multiple@bool: yes
records:
  automation/mailReceived:
    fields:
      name: example.ticket.auto_assignment.roundRobin
      extension_id: cerb.trigger.mail.received
      description@text:
      script@raw:
        start:
          set/init:
            config@json: {{cerb_workflow_config('example.ticket.auto_assignment')|json_encode}}
          
          storage.get/counter:
            output: counter
            inputs:
              key: example.ticket.auto_assignment.roundRobin.counter
              default: -1
        
          storage.set:
            inputs:
              key: example.ticket.auto_assignment.roundRobin.counter
              value: {{counter + 1}}
          
          set/worker:
            assignee_id@int: {{cycle(config.worker_ids, counter + 1)}}
          
          outcome/hasAssignee:
            if@bool: {{assignee_id}}
            then:
              record.update:
                output: updated_record
                inputs:
                  record_type: ticket
                  record_id: {{message_ticket_id}}
                  fields:
                    owner_id@int: {{assignee_id}}
      policy_kata@raw:
        commands:
          storage.get:
            deny/key@bool: {{inputs.key is not prefixed ('example.ticket.auto_assignment.roundRobin.')}}
            allow@bool: yes
          storage.set:
            deny/key@bool: {{inputs.key is not prefixed ('example.ticket.auto_assignment.roundRobin.')}}
            allow@bool: yes
          record.update:
            deny/type@bool: {{inputs.record_type is not record type ('ticket')}}
            allow@bool: yes
  automation_event_listener/mailReceivedListener:
    fields:
      name: Round-Robin Assignment
      event_name: mail.received
      priority@int: 50
      is_disabled: 0
      event_kata@raw:
        automation/roundRobin:
          uri: cerb:automation:example.ticket.auto_assignment.roundRobin
          disabled@bool:
            {{message_ticket_bucket_id not in cerb_workflow_config('example.ticket.auto_assignment','bucket_ids')}}
```

**Comment by jstanden** [comment]
This example uses load-leveling and custom fieldsets rather than round-robin.

```yaml
workflow:
  name: example.ticket.auto_assignment
  version: 2025-01-16T23:29:18Z
  description: Auto-assign new tickets to a list of group workers using load leveling
  website: https://cerb.ai/resources/workflows/
  requirements:
    cerb_version: >=11.0 <11.1
    cerb_plugins: cerberusweb.core,
records:
  automation/mailReceived:
    fields:
      name: example.ticket.auto_assignment.loadLeveling
      extension_id: cerb.trigger.mail.received
      description@text:
      script@raw:
        start:
          set/init:
            config@json: {{cerb_workflow_config('example.ticket.auto_assignment')|json_encode}}
        
          data.query/loadLeveling:
            output: results
            inputs:
              query@text:
                type:worklist.subtotals
                of:ticket
                by.count:[owner.id~-25]
                query:(status:o owner.id:[{{message_ticket_group_autoAssignment_assignee|join(',')}}])
                format:dictionaries
            on_success:
              set:
                assignee_id@trim,int:
                  {% set min_assigned = min(results.data|column('count')) %}
                  {% set workers = results.data|filter((o) => o.count == min_assigned) %}
                  
                  {# If more than one tied for lowest, randomly pick one #}
                  {% if workers|length > 1 %}
                  {% set workers = shuffle(workers) %}
                  {% endif %}
                  
                  {{workers|first.owner_id|default(0)}}
              var.unset:
                inputs:
                  key@csv: results
        
          outcome/hasAssignee:
            if@bool: {{assignee_id}}
            then:
              record.update:
                on_simulate:
                output: updated_record
                inputs:
                  record_type: ticket
                  record_id: {{message_ticket_id}}
                  fields:
                    owner_id@int: {{assignee_id}}
      policy_kata@raw:
        commands:
          data.query:
            deny/type@bool: {{query.type != 'worklist.subtotals'}}
            allow@bool: yes
          record.update:
            deny/type@bool: {{inputs.record_type is not record type ('ticket')}}
            allow@bool: yes
  automation_event_listener/mailReceivedListener:
    fields:
      name: Auto-Assignment
      event_name: mail.received
      priority@int: 50
      is_disabled: 0
      event_kata@raw:
        automation/loadLeveling:
          uri: cerb:automation:example.ticket.auto_assignment.loadLeveling
          disabled@bool:
            {{
              message_ticket_owner_id is not empty 
              and message_ticket_group_autoAssignment_assignee is empty
            }}          
  custom_fieldset/fieldset_auto_assignment:
    fields:
      name: Auto-Assignment
      context: group
      owner__context: app
      owner_id: 0
  custom_field/fieldset_auto_assignment_assignee:
    fields:
      name: Assignees
      context: group
      uri: autoAssignment_assignee
      type: cerb.custom_field.record.links
      pos@int: 0
      custom_fieldset_id: {{records.fieldset_auto_assignment.id}}
      params:
        context: cerberusweb.contexts.worker
```
