### ISSUE TITLE
[Automation/Cookbook] Add a recipe for loading a record inline with `set:`

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#118]
This shows you can add a key expandable placeholder by just naming a common (arbitrary) prefix and using the `_context` and `id` suffixes.

```
start:
  set:
    ticket__context: ticket
    ticket_id: 1
  return:
    output: {{ticket__label}}
```
