### ISSUE TITLE
[Automation/Cookbook] Breaking a while loop with a condition

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#127]
This is an infinite loop that will break with 25% probability (`random(n)` is a random number from `0` to `n` inclusive). The [while:](https://cerb.ai/docs/automations/commands/while/) loop repeats until `isLooping` is `false`.

At the end of the execution, the `counter` value shows how many times it iterated, and it will be different for each execution.

```yaml
start:
  set:
    isLooping@bool: yes
    counter@int: 0
  
  while/exampleLoop:
    if@bool: {{isLooping}}
    do:
      set:
        counter@int: {{counter + 1}}
        isLooping@bool: {{3 != random(3)}}
```

Loops like this can be used around an `await:` to repeat an interaction until stopped. For instance, the AI image generation guide.
