### ISSUE TITLE
[Automations/Cookbook] Conditional branching statements (e.g. switch, if/else-if)

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#128]
These are conditional branching examples.

This approach works best if you need to conditionally run commands for an option:

```yaml
start:
  set:
    option: 2

  decision:
    outcome/option1:
      if@bool: {{1 == option}}
      then:
        return:
          output: You picked option 1.
    outcome/option2:
      if@bool: {{2 == option}}
      then:
        return:
          output: You picked option 2.
    outcome/option3:
      if@bool: {{3 == option}}
      then:
        return:
          output: You picked option 3.          
```

If you just need to set a value conditionally, this is much simpler:

```yaml
start:
  set:
    option: 2
    options:
      1: You picked option 1
      2: You picked option 2
      3: You picked option 3

  return:
    output: {{options[option]}}
```
