### ISSUE TITLE
[Automations/Cookbook] HTTP GET request

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#129]
```yaml
start:
  http.request/get:
    output: http_response
    inputs:
      method: GET
      url: https://cerb.ai/
    on_success:
    on_error:
```

Policy:

```yaml
commands:
  http.request:
    deny/method@bool: {{inputs.method not in ['GET']}}
    deny/url@bool: {{inputs.url is not prefixed ('http://','https://')}}
    allow@bool: yes
```
