### ISSUE TITLE
[Automations/Cookbook] HTTP POST request with a JSON payload

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#130]
```yaml
start:
  http.request/get:
    output: http_response
    inputs:
      method: POST
      url: https://cerb.example/api/endpoint/
      headers:
        Content-Type: application/json
      body:
        name_first: Kina
        name_last: Halpue
        email: kina.halpue@cerb.example
    on_success:
    on_error:
```

Policy:

```yaml
commands:
  http.request:
    deny/method@bool: {{inputs.method not in ['POST']}}
    deny/url@bool: {{inputs.url is not prefixed ('http://','https://')}}
    allow@bool: yes
```
