### ISSUE TITLE
[Automations/Cookbook] Sheet of records with paging in an interaction.worker

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#133]
```yaml
start:
  await:
    form:
      title: Sheet with paging
      elements:
        sheet/prompt_results:
          label: Results:
          data:
            automation:
              uri: cerb:automation:cerb.data.records
              inputs:
                record_type: ticket
                query_required: status:o
          limit: 10
          schema:
            layout:
              title_column:  _label
              headings@bool: yes
              paging@bool: yes
            columns:
              text/_label:
                params:
                  bold@bool: yes
              text/status:
              card/group_id:
                label: Group
              card/owner_id:
                label: Owner
              date/updated:
```
