### ISSUE TITLE
[Automations/Cookbook] Optional keys based on a conditional value

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#134]
```yaml
start:
  set:
    record:
      name: Kina Halpue
      email: kina@cerb.example
      region: US
  return:
    output:
      name: {{record.name}}
      email: {{record.email}}
      gdpr@optional,bool: {{'EU' == record.region ? true}}
```

The [@optional](https://cerb.ai/docs/automations/#annotations) annotation removes a key when the value is empty.

In this example, we're converting the `record.region` value `EU` -> `true` and everything else to `null`. When `null` the entire `gdpr` key is omitted from the output.
