### ISSUE TITLE
[Automations/Cookbook] Simulate random failures in an HTTP GET request

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#135]
The `on_simulate:` event works in the automation editor and is ignored in production.

The `random(1)` function returns a value of `0` or `1` (50% chance of either).

`simulate.success:` mocks the `http.request:` response and triggers the `on_success:` event.

`simulate.error:` triggers the `on_error:` event.

```yaml
start:
  http.request/get:
    output: http_response
    inputs:
      method: GET
      url: https://cerb.ai/
    on_simulate:
      decision:
        outcome/error500:
          if@bool: {{0 == random(1)}}
          then:
            simulate.error:
              status_code@int: 500
              body: Error!
        outcome/ok200:
          then:
            simulate.success:
              status_code@int: 200
              body: Success!
    on_error:
      log.error: This is an error message
    on_success:
```

Policy:

```yaml
commands:
  http.request:
    deny/method@bool: {{inputs.method not in ['GET']}}
    allow@bool: yes
```
