### ISSUE TITLE
[Automations/Cookbook] Generate the underlying SQL statement for any record search query

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#136]
This is useful for debugging slow search queries without having to capture them in the MySQL `slow_query` log or with `SHOW FULL PROCESSLIST` at the console. This can be shared with developers or used in the MySQL console with `EXPLAIN` to troubleshoot.

```yaml
start:
  api.command:
    output: results
    inputs:
      name: cerb.commands.worklist.query.debug
      params:
        record_type: ticket
        query: status:o created:"-1 week" group:(name:"Support")
```

Output:

```yaml
results:
  sql: SELECT t.id AS t_id , t.updated_date AS t_updated_date FROM ticket t  WHERE
    t.status_id IN (0)  AND t.created_date BETWEEN 1736496000 and 1737155624 AND t.group_id
    IN (SELECT g.id FROM worker_group g WHERE (g.name = 'Support') )  ORDER BY t_updated_date
    DESC LIMIT 0,10
```

Policy:

```yaml
commands:
  api.command:
    deny/name@bool: {{inputs.name not in ['cerb.commands.worklist.query.debug']}}
    allow@bool: yes
```
