### ISSUE TITLE
[Automations/Cookbook] Escape untrusted user input in data queries

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#137]
The `query_params:` option is a key/value object. The `${...}` syntax in a data query references those keys.

The reason this is more secure is because `${...}` placeholders aren't evaluated until the query is parsed, so they can never modify the structure of the query.

```yaml
start:
  data.query:
    output: results
    inputs:
      query@text:
        type:worklist.records
        of:ticket
        query:(
          participant:(email:${email})
          status:o
        )
        format:dictionaries
      query_params:
        email: customer@cerb.example
```

Policy:

```yaml
commands:
  data.query:
    deny/type@bool: {{query.type != 'worklist.records'}}
    allow@bool: yes
```

Without escaping/sanitization, malicious user input can perform query injection like:

```yaml
start:
  set:
    email: "blah") OR (id:>0
  data.query:
    output: results
    inputs:
      query@text:
        type:worklist.records
        of:ticket
        query:(
          participant:(email:{{email}})
          status:o
        )
        format:dictionaries
```

This example breaks out of the `participant:(email:)` filter and returns all open tickets. The `email` placeholder here could come from a web form, etc.
