### ISSUE TITLE
[Automations/Cookbook] Setting dynamic values with the ternary operator

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#138]
```yaml
start:
  set:
    is_admin@bool: true
  return:
    is_admin: {{is_admin ? 'yes' : 'no'}}
```

The syntax is `{{expression ? if_true : if_false}}`

**Comment by JC3P0** [comment]
I was wondering if Cerb supports checking multiple conditions with ternary operators?
For example, something like this:
```yaml
start:
  set:
    is_admin@bool: false
    is_manager@bool: true
  return:
    has_role: {{is_admin ? 'admin' : is_manager ? 'manager' : 'worker'}}
```
Would this work in Cerb / make sense to do so? If so should we add an example to check multiple roles?

**Comment by jstanden** [comment]
@JC3P0 yeah, you can nest them like that. It helps to use parentheses once you're grouping more than one of them in the else clause to keep it separate.

```yaml
start:
  set:
    is_admin@bool: n
    is_manager@bool: n
  return:
    has_role: {{is_admin ? 'admin' : (is_manager ? 'manager' : 'worker')}}
```

At that point, though, this approach is cleaner:

```yaml
start:
  set:
    is_admin@bool: n
    is_manager@bool: n
  return:
    has_role@trim:
      {% if is_admin %}admin
      {% elseif is_manager %}manager
      {% else %}worker
      {% endif %}
```

We definitely could find a place for that example in the cookbook.
