### ISSUE TITLE
[Automations/Cookbook] Setting dynamic values with a dictionary

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#139]
A single value can be expanded to a dictionary of attributes.

For instance, a worker can select a row in a [sheet](https://cerb.ai/docs/sheets/) that returns the `id` of a selected model. Subsequent logic can look up the model's details using that key.

```yaml
start:
  set:
    models:
      llama3.3:
        tools@bool: yes
        params: 70b
      phi4:
        tools@bool: no
        params: 14b
      mistral:
        tools@bool: yes
        params: 7b
  
  return:
    output@text:
      {% for model in models|keys %}
      {{model}} has {{models[model].params}} parameters{{models[model].tools ? ' and supports tools'}}.
      {% endfor %}
```

Output:

```yaml
output: |
  llama3.3 has 70b parametersand supports tools.
  phi4 has 14b parameters.
  mistral has 7b parametersand supports tools.
```
