### ISSUE TITLE
[Automations/Cookbook] Set a key with a dynamic name

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#140]
You can't use scripting in a KATA key, but you can still set a dynamic key name with `var.set:`:

```yaml
start:
  var.set/random:
    inputs:
      key: random_{{random_string(6)}}
      value: {{random_string(6)}}
```

This also works for key names that aren't valid in KATA, such as those containing `:` or spaces.
