### ISSUE TITLE
[Automations/Cookbook] Iterate placeholders with unknown names

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#141]
Let's assume for some reason you have placeholders but don't know their keys in advance.

You can use `cerb_placeholders_list()` to iterate through all of the existing placeholders. The function also accepts an optional prefix argument to filter the placeholders by name.

```yaml
start:
  repeat:
    each@csv: {{range(1,10)|join(',')}}
    as: i
    do:
      var.set:
        inputs:
          key: random_{{random_string(6)}}
          value: {{random_string(6)}}
  
  return:
    output@text:
      {% for key, value in cerb_placeholders_list('random_') %}
      random_{{key}}: {{value}}
      {% endfor %}
```

Output:

```yaml
__return:
  output: |
    random_3ALY8R: BUVA2H
    random_NEV48A: YD2HH2
    random_9ZHA4L: 7VG3ZT
    random_3T6QXX: Q5KKBD
    random_XDDBKN: E8VHTY
    random_394CGD: Q5WW15
    random_Z2GZSB: SM4PGK
    random_K8VCP4: 637HZ3
    random_4S3HAG: DVHQB7
    random_M31U6N: 7G5SY8
```

This example sets random key names, but can still iterate them using the common prefix.
