### ISSUE TITLE
[Automations/Cookbook] Escape placeholders in a value

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#142]
Use the [@raw](https://cerb.ai/docs/automations/#annotations) annotation to preserve placeholders in a value. This is particularly useful in [sheets](https://cerb.ai/docs/sheets/).

```yaml
start:
  return:
    unescaped: You escape {{placeholders}} with the `@raw` annotation
    escaped@raw: You escape {{placeholders}} with the `@raw` annotation
```

Output:

```yaml
__return:
  unescaped: You escape  with the `@raw` annotation
  escaped: You escape {{placeholders}} with the `@raw` annotation
```
