### ISSUE TITLE
[Automations/Cookbook] Read a ZIP manifest and extract files from an attachment record

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#143]
Read the manifest of a `.zip` attachment record:

```yaml
start:
  data.query/zip:
    inputs:
      query@text:
        type:attachment.manifest
        id:1234
        format:dictionaries
    output: results
```

Use `filter:` to look for specific filename patterns:

```yaml
start:
  data.query/zip:
    inputs:
      query@text:
        type:attachment.manifest
        id:1234
        filter:*.txt
        format:dictionaries
    output: results
```

Extract a specific file path from the ZIP:

```yaml
start:
  file.read:
    output: file_contents
    inputs:
      uri: cerb:attachment:1234
      extract: README.txt
      filters:
        gzip.decompress:
```

Use this policy:

```yaml
commands:
  data.query:
    deny/type@bool: {{query.type != 'attachment.manifest'}}
    allow@bool: yes
  file.read:
    allow@bool: yes
```

For testing, see: #144
