### ISSUE TITLE
[Automations/Cookbook] Create a ZIP file attachment

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#144]
The `file.write:` command can create a ZIP archive with files from arbitrary text, temporary automation resources, or existing file attachments.

```yaml
start:
  file.write:
    output: tmp_file
    inputs:
      mime_type: application/zip
      content:
        zip:
          files:
            file/readme:
              path: README.txt
              bytes@text:
                This is the README file.
            file/docker:
              path: docker/Dockerfile
              bytes@text:
                FROM ubuntu:24.04
  
  record.create/file:
    output: new_file
    inputs:
      record_type: attachment
      fields:
        name: example.zip
        mime_type: application/vnd.cerb.uri
        content: {{tmp_file.uri}}
```

Policy:

```yaml
commands:
  file.write:
    allow@bool: yes
  record.create:
    deny/type@bool: {{inputs.record_type is not record type ('attachment')}}
    allow@bool: yes
```

The `record.create` command uses the `application/vnd.cerb.uri` MIME type to refer to the existing `cerb:automation_resource:` URI as the content.
