### ISSUE TITLE
[Automations/Cookbook] Using a custom sort comparator

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#146]
The `|sort` filter can take an arrow function for your own comparator:
https://twig.symfony.com/doc/3.x/filters/sort.html

```yaml
start:
  set:
    example_data@json: 
      [
        {"name": "Item 1", "key": "ZZZ"},
        {"name": "Item 2", "key": "MMM"},
        {"name": "Item 3", "key": "AAA"}
      ]
  return:
    sorted: {{example_data|sort((a,b)=> a.key<=>b.key)|column('name')|join(', ')}}

```

That will output "Item 3, Item 2, Item 1" since it's sorting by the `key` property of each object in the list.
