### ISSUE TITLE
[Automations/Cookbook] Fetch the email addresses of all workers in a given group

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#150]
To fetch the email addresses of all the workers in a given group:

```yaml
start:
  record.search/workers:
    output: results_worker
    inputs:
      record_type: worker
      record_query: isDisabled:n group:(name:"Support")
      record_expand: address
  set:
    emails@csv: {{results_worker|column('address_email')|join(',')}}
```

Policy:

```yaml
commands:
  record.search:
    deny/type@bool: {{inputs.record_type is not record type ('workers')}}
    allow@bool: yes
```
