### ISSUE TITLE
[Automations/Cookbook] Relay email messages to workers

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#151]
Relay to workers from automations:

```yaml
start:
  api.command:
    inputs:
      name: cerb.commands.email.relay
      params:
        message_id@int: 1234
        emails@csv: kina@cerb.example, mara@cerb.example
    output: results
```

See: https://cerb.ai/guides/mail/relaying/
