### ISSUE TITLE
[Automations/Cookbook] Report a ticket as spam

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#152]
Report a ticket as spam from automations:

```yaml
start:
  api.command:
    output: results
    inputs:
      name: cerb.commands.email.spam.train
      params:
        ticket_id@int: 1234
```

Policy:

```yaml
commands:
  api.command:
    deny/name@bool: {{inputs.name not in ['cerb.commands.email.spam.train']}}
    allow@bool: yes
```
