### ISSUE TITLE
[Automations/Cookbook] Filter an object/dictionary by key name

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#153]
The `|filter(v)` modifier will work on the array values by default. To check the keys, use `(v,k)` in your array function.

```yaml
start:
  set:
    message_headers:
      x-gitlab-project: abc123
      x-blah: def456
      x-example: ghi789
  return:
    gitlab_headers@json: {{message_headers|filter((v,k) => k is prefixed ('x-gitlab'))|json_encode}}
```

Output:

```yaml
__return:
  gitlab_headers:
    x-gitlab-project: abc123
```
