### ISSUE TITLE
[Automations/Cookbook] Filter array values with custom logic (arrow function)

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#154]
This example returns the multiples of 5 in a list of numbers from 1 to 100.

```
start:
  set:
    numbers@csv: {{range(1,100)|join(',')}}
  return:
    multiples5@csv: {{numbers|filter((n,k) => 0 == n % 5)|join(',')}}
```

The `|filter` modifier can take an arrow function (`(n,k) => expression`) as its first argument. This is evaluated for each array item. If it returns `false` an item is removed from the list.

See: https://cerb.ai/docs/scripting/filters/#filter
