### ISSUE TITLE
[Automations/Cookbook] Apply a function to each item in a list (map)

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#155]
Use the `|map` filter to apply a function to each item in a list.

For instance, for the numbers from 1 to 10, return their squares and cubes:

```yaml
start:
  set:
    numbers@csv: {{range(1,10)|join(',')}}
  return:
    squares@json: {{numbers|map((n,k) => n ** 2)|json_encode}}
    cubes@json: {{numbers|map((n,k) => n ** 3)|json_encode}}
```

Output:

```yaml
__return:
  squares:
  - 1
  - 4
  - 9
  - 16
  - 25
  - 36
  - 49
  - 64
  - 81
  - 100
  cubes:
  - 1
  - 8
  - 27
  - 64
  - 125
  - 216
  - 343
  - 512
  - 729
  - 1000
```
