### ISSUE TITLE
[Automations/Cookbook] Pass in an arbitrary record type and ID as input

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#157]
```yaml
inputs:
  text/record_type:
    type: record_type
    required@bool: yes
  text/record_id:
    type: number
    required@bool: yes

start:
  set:
    record__context@key: inputs:record_type
    record_id@key: inputs:record_id
  
  return:
    output: {{record__label}}
```

Related to #118
