### ISSUE TITLE
[Automations/Cookbook] Validate an OAuth2/JWT bearer token

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#158]
Create an example OAuth2 token from **Cerb >> Setup >> Developers >> OAuth2 Token Generator**.

In a webhook automation you can use the `cerb.commands.oauth2.token.validate` action with `api.command:` to validate the JWT bearer token given in the request:

```yaml
start:
  set:
    request_headers:
      authorization: Bearer: eyJ0eXAiOiJKV1QiLCJhbGc[...]
  api.command:
    inputs:
      name: cerb.commands.oauth2.token.validate
      params:
        token: {{request_headers.authorization|split(' ')|last}}
    output: results
    on_error:
```

Policy:

```yaml
commands:
  api.command:
    deny/name@bool: {{inputs.name not in ['cerb.commands.oauth2.token.validate']}}
    allow@bool: yes
```

The `results` placeholder will have keys for your OAuth `app_`, as well as `token_scopes`, `token_type`, `token_expires_at` and `worker_`.

We don't assume a Bearer token for an inbound request is specifically in Cerb's token format. For instance, you could issue your own API keys and use an `Authorization: Bearer blah-token` header that your webhook verifies.

Some webhook callers send their own secret with the POST for you to verify, or they HMAC sign the requests with a shared secret. We tried to keep it flexible.
