### ISSUE TITLE
[Automations/Cookbook] Create an array of random numbers

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#159]
```yaml
start:
  return:
    values@json: {{range(1,10)|map((v) => random(0,100))|json_encode}}
```

Output:

```yaml
__return:
  values:
  - 31
  - 24
  - 25
  - 15
  - 53
  - 18
  - 73
  - 93
  - 46
  - 92
```
