### ISSUE TITLE
[Automations/Cookbook] Log retroactive custom metric values

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#160]
See: https://cerb.ai/docs/metrics/

```yaml
start:
  metric.increment:
    inputs:
      metric_name: example.metric.name
      timestamp@date: Jan 1 2025 5pm America/Los_Angeles
      values@csv: 1,2,3
```

From **Setup >> Developers >> Data Query Tester**, verify the sampled data:

```
type:metrics.timeseries
series.intervals:(
  metric:example.metric.name
  function:average
  missing:zero
)
period:day
range:"this month"
format:timeseries
```
