### ISSUE TITLE
[Automations/Cookbook] Create a comment record

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#164]
```yaml
start:
  record.create/comment:
    output: new_comment
    inputs:
      record_type: comment
      fields:
        author__context: app
        author_id@int: 0
        target__context: ticket
        target_id@int: 123
        is_markdown@int: 1
        comment@text:
          This is a **comment** from an automation.
```

`author__context:` can be one of: app, role, group, worker

`target__context:` is the target record type.

Policy:

```yaml
commands:
  record.create:
    deny/type@bool: {{inputs.record_type is not record type ('comment')}}
    allow@bool: yes
```
