### ISSUE TITLE
[Automations/Cookbook] Add a prefix to each line in a block of text

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#166]
In this example we quote a prior email message using  the standard `>` character.

```yaml
start:
  set:
    original_message@text:
      This is quoted text
      From a prior conversation
      and we want to quote it
  return:
    new_message@text:
      {{original_message|indent('> ')}}
      
      ... and this is our reply.
```

Output:

```yaml
__return:
  new_message: |-
    > This is quoted text
    > From a prior conversation
    > and we want to quote it

    ... and this is our reply.
```
