### ISSUE TITLE
[Automations/Cookbook] Loop through each record in search results

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#167]
To run automation commands on each record in search results, use `repeat:`.

The best practice is to loop through the IDs and reference the records like `results[id]`. This is more efficient than looping through the records directly since it doesn't duplicate the list during iteration.

```yaml
start:
  record.search:
    output: tickets
    inputs:
      record_type: ticket
      record_query: status:o limit:10
      record_expand: customfields
  
  repeat:
    each@csv: {{tickets|keys|join(',')}}  
    as: ticket_id
    do:
      log: Editing #{{ticket_id}} {{tickets[ticket_id]._label}}
```

Policy:

```yaml
commands:
  record.search:
    deny/type@bool: {{inputs.record_type is not record type ('ticket')}}
    allow@bool: yes
```
