### ISSUE TITLE
[Automations/Cookbook] Add a column to a list of dictionaries

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#179]
The `|merge` filter combines two arrays or objects. We use it in `|map` to add a new random `age` column to the list of people.

Automation:
```yaml
start:
  set:
    people:
      kina:
        name: Kina Halpue
        email: kina@cerb.example
      milo:
        name: Milo Dade
        email: milo@cerb.example
  set/merge:
    people@json: {{people|map((v) => v|merge({'age':random(20,65)}))|json_encode}}
```

Output:
```yaml
people:
  kina:
    name: Kina Halpue
    email: kina@cerb.example
    age: 35
  milo:
    name: Milo Dade
    email: milo@cerb.example
    age: 33
```
