### ISSUE TITLE
[Automations/Cookbook] Trim whitespace in scripting tags

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#189]
Adding a dash `-` to an opening or closing scripting tag (`{{-`, `{%-`) will respectively trim all leading or trailing whitespace.

Automation:
```yaml
start:
  return:
    output@text:
      This text
      
      {{-" has no leading or trailing whitespace "-}}
      
      in it.
```

Output:
```yaml
__return:
  output: This text has no leading or trailing whitespace in it.
```

Also mention: https://cerb.ai/docs/scripting/commands/#spaceless
