### ISSUE TITLE
[Automations/Cookbook] Set deeply nested keys in arrays and values

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#190]
See: https://cerb.ai/docs/scripting/arrays-objects/#modifying-arrays-and-objects & https://cerb.ai/docs/scripting/functions/#dict_set

Using `dict_set()`

Automation:
```yaml
start:
  set:
    worker@json:
      {% set var = {"group": {}} %}
      {% set var = dict_set(var, 'group.name', 'Support') %}
      {% set var = dict_set(var, 'group.manager.name.first', 'Kina') %}
      {% set var = dict_set(var, 'group.manager.name.last', 'Halpue') %}
      {{var|json_encode}}
  return:
    worker@key: worker
```

Output:
```yaml
__return:
  worker:
    group:
      name: Support
      manager:
        name:
          first: Kina
          last: Halpue
```
