### ISSUE TITLE
[Automations/Cookbook] Find the difference between two lists

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#191]
See: https://cerb.ai/docs/scripting/functions/#array_diff

The [array_diff()](https://cerb.ai/docs/scripting/functions/#array_diff) function returns the items in the second array that are not present in the first array.

Automation:
```yaml
start:
  set:
    array1@csv: Apple, Google, Microsoft
    array2@csv: Apple, Microsoft, Cerb
    diff@csv: {{array_diff(array2, array1)|join(', ')}}
  return:
    output: These are new: {{diff|join(', ')}}
```

Output:
```yaml
__return:
  output: 'These are new: Cerb'
```
