### ISSUE TITLE
[Automations/Cookbook] Format dates and timezones

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#192]
See: https://cerb.ai/docs/scripting/dates/ & https://www.php.net/manual/en/datetime.format.php

Automation:
```yaml
start:
  return:
    now: {{'now'|date('F d, Y h:ia T')}}
    timezone: {{'now'|date('F d, Y h:ia T', 'Europe/Berlin')}}
    tomorrow: {{'tomorrow 5pm'|date('D, d F Y H:i T')}}
    two_weeks: {{'+2 weeks 08:00'|date('Y-m-d h:ia T')}}
    rfc2822: {{'now'|date('r')}}
    iso8601: {{'now'|date('c')}}
    unix@int: {{'now'|date('U')}}
```

Output:
```yam
__return:
  now: January 29, 2025 02:02pm PST
  timezone: January 29, 2025 11:02pm CET
  tomorrow: Thu, 30 January 2025 17:00 PST
  two_weeks: 2025-02-12 08:00am PST
  rfc2822: Wed, 29 Jan 2025 14:02:39 -0800
  iso8601: "2025-01-29T14:02:39-08:00"
  unix: 1738188159l
```
