### ISSUE TITLE
[Automations/Cookbook] Calculate the sum or product of an array of numbers

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#196]
See: https://cerb.ai/docs/scripting/functions/#array_sum + https://cerb.ai/docs/scripting/filters/#reduce

Automation:
```yaml
start:
  set:
    numbers@csv: 1, 9, 2002, 4, 27, 2001
  return:
    sum@int: {{array_sum(numbers)}}
    product@int: {{numbers|reduce((carry,n) => carry * n, 1)}}
```

Output:
```yaml
__return:
  sum: 4044
  product: 3893833944
```
