### ISSUE TITLE
[Automations/Cookbook] Check if a date is in the past or future

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#197]
See: https://cerb.ai/docs/scripting/filters/#date

The `|date('U')` converts dates to Unix timestamps (seconds since 1970-01-01 00:00:00 UTC) for simpler comparsions.

Automation:
```yaml
start:
  set:
    sla_expiration@date: +2 weeks
  return:
    output@text:
      {% if sla_expiration >= 'now'|date('U') %}
      Your SLA coverage is active.
      {% else %}
      Your SLA coverage has expired.
      {% endif %}
```

Output:
```yaml
__return:
  output: |
    Your SLA coverage is active.
```
