### ISSUE TITLE
[Automations/Cookbook] Loop through a range of numbers

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#198]
See: https://cerb.ai/docs/scripting/functions/#range

Automation:
```yaml
start:
  return:
    output@text:
      {% for n in range(1,5) %}
      {{n}}...
      {% endfor %}
```

Output:
```yaml
__return:
  output: |
    1...
    2...
    3...
    4...
    5...
```

Using `step`:

Automation:
```yaml
start:
  return:
    output@text:
      {% for n in range(1,10,step=2) %}
      {{n}}...
      {% endfor %}
```

Output:
```yaml
__return:
  output: |
    1...
    3...
    5...
    7...
    9...
```
