### ISSUE TITLE
[Automations/Cookbook] Apply filters to a block of text

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#200]
See: https://twig.symfony.com/doc/3.x/tags/apply.html

Rather than a variable. Also give an example of chaining filters with `|`. This is occasionally useful in a template (e.g. snippets).

Automation:
```yaml
start:
  return:
    output@text:
      {% apply upper %}
      All of this text will be uppercase.
      On every line.
      {% endapply %}
```

Output:
```yaml
__return:
  output: |
    ALL OF THIS TEXT WILL BE UPPERCASE.
    ON EVERY LINE.
```
