### ISSUE TITLE
[Automations/Cookbook] Change the case type of text

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#205]
Automation:
```yaml
start:
  set:
    sentence: This is a sentence.
  return:
    upper: {{sentence|upper}}
    lower: {{sentence|lower}}
    capitalized: {{sentence|capitalize}}
    title: {{sentence|title}}
```

Output:
```yaml
__return:
  upper: THIS IS A SENTENCE.
  lower: this is a sentence.
  capitalized: This is a sentence.
  title: This Is A Sentence.
```
