### ISSUE TITLE
[Automations/Cookbook] Calculate the length of text or a list

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#206]
Automation:
```yaml
start:
  return:
    list_len@int: {{[1,2,3,4,5,6,7,8,9,10]|length}}
    text_len@int: {{'This is some text'|length}}
```

Output:
```yaml
__return:
  list_len: 10
  text_len: 17
```
