### ISSUE TITLE
[Automations/Cookbook] Reverse text or a list

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#207]
`|reverse(true)` preserves array keys.

Automation:
```yaml
start:
  return:
    reversed_list@csv: {{[1,2,3,4,5]|reverse|join(',')}}
    reversed_text: {{"This is text to reverse."|reverse}}
```

Output:
```yaml
__return:
  reversed_list:
  - "5"
  - "4"
  - "3"
  - "2"
  - "1"
  reversed_text: .esrever ot txet si sihT
```
