### ISSUE TITLE
[Automations/Cookbook] Batch list items into sets

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#208]
Automation:
```yaml
start:
  set:
    items@json: [1,2,3,4,5,6,7,8,9,10]
  return:
    batches: {{items|batch(size=3, fill=-1, preserve_keys=false)|json_encode}}
```

Output:
```yaml
__return:
  batches: '[[1,2,3],[4,5,6],[7,8,9],[10,-1,-1]]'
```
