### ISSUE TITLE
[Automations/Cookbook] Shuffle a list or string

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#209]
Automation:
```yaml
start:
  return:
    shuffled_list: {{shuffle([1,2,3,4,5,6,7,8,9,10])|json_encode}}
    shuffled_text: {{shuffle("abcdefghijklmnopqrstuvwxyz"|split(''))|join('')}}
```

Output:
```yaml
__return:
  shuffled_list: '[2,4,5,1,7,10,8,9,6,3]'
  shuffled_text: wrgpudtahnqjemklsfizoybvcx
```
