### ISSUE TITLE
[Automations/Cookbook] Split text with a delimiter

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#210]
https://cerb.ai/docs/scripting/filters/#split

You can split these into separate examples.

Automation:
```yaml
start:
  return:
    split_list@json: {{"1,2,3"|split(',')|json_encode}}
    split_uris@json: {{"cerb:ticket:123"|split(':')|json_encode}}
    split_limit@json: {{"/usr/share/html/cerb/storage/"|trim('/')|split('/', limit=2)|json_encode}}
    split_chunks@json: {{"abcdefgh"|split('',limit=2)|json_encode}}
```

Output:
```yaml
__return:
  split_list:
  - "1"
  - "2"
  - "3"
  split_uris:
  - cerb
  - ticket
  - "123"
  split_limit:
  - usr
  - share/html/cerb/storage
  split_chunks:
  - ab
  - cd
  - ef
  - gh
```
