### ISSUE TITLE
[Automations/Cookbook] Return the keys of an array or dictionary

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#211]
Automation:
```yaml
start:
  set:
    person:
      name_first: Kina
      name_last: Halpue
      email: kina.halpue@cerb.example
  return:
    keys@csv: {{person|keys|join(', ')}}
```

Output:
```yaml
__return:
  keys:
  - name_first
  - name_last
  - email
```
