### ISSUE TITLE
[Automations/Cookbook] Convert HTML to Markdown

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#212]
Automation:
```yaml
start:
  set:
    message_html@text:
      <html><body><h1>Title</h1>This is an <b>HTML</b> message</body></html>
  return:
    output: {{message_html|html_to_text(truncate=50000)}}
```

Output:
```yaml
__return:
  output: |-
    # Title
    This is an HTML message
```
