### ISSUE TITLE
[Automations/Cookbook] Convert Markdown to HTML

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#213]
`is_untrusted` sanitizes HTML output (e.g. script blocks and images).

Automation:
```yaml
start:
  set:
    markdown_text@text:
      # Title
      This is a **Markdown** message.
  return:
    output: {{markdown_text|markdown_to_html(is_untrusted=true)}}
```

Output:
```yaml
__return:
  output: |-
    <h1>Title</h1>
    <p>This is a <strong>Markdown</strong> message.</p>
```
