### ISSUE TITLE
[Solutions/Automations] Parse VObject attachments

### ISSUE THREAD

**Issue by jstanden** [cerb/cerb.github.io#270]
Assuming a `text/calendar` vCalendar attachment (e.g. invite/approval), or something like a VCard.

Wikipedia: https://en.wikipedia.org/wiki/ICalendar#vCalendar_1.0 + https://en.wikipedia.org/wiki/VCard

An LLM generated example:

```vobject
BEGIN:VCARD
VERSION:3.0
FN:John Doe
N:Doe;John;;;
ORG:Example Inc.
TITLE:Software Engineer
TEL;TYPE=WORK,VOICE:+1-234-567-8901
EMAIL:john.doe@example.com
ADR;TYPE=WORK:;;123 Main St;New York;NY;10001;USA
URL:https://example.com
END:VCARD
```

Automation:
```yaml
start:
  file.read:
    output: results
    inputs:
      uri: cerb:attachment:12345
    on_success:
      return:
        vcalendar@json: {{vobject_parse(results.bytes)|json_encode}}
```

Policy:
```yaml
commands:
  file.read:
    allow@bool: yes
```

Output:
```yaml
__exit: return
__return:
  vcalendar:
    VCALENDAR:
    - props:
        PRODID:
        - params: []
          value: -//Microsoft Corporation//Outlook 16.0 MIMEDIR//EN
        VERSION:
        - params: []
          value: "2.0"
        METHOD:
        - params: []
          value: REPLY
#...
```
